feat: Add alternative methods, so `Bytes` is not required
CrabCraftDev/CrabNBT pull request #19
Opened 2024-09-18 15:08 UTC by Norbiros

Fixes: #17

This solution, while not perfect, enables full utilization of CrabNBT without needing to include `bytes` crate in your project. 

In future, I'll redesign this to improve performance (writing directly to `Vec` instead of serializing bytes and then pushing it) and usability, but this will require changes to public methods and a new major version (see #18 for details).

2024-09-18 15:19 UTC, SzczurekYT commented
So this just adds wrapper functions around current code which still use bytes right?

2024-09-18 15:22 UTC, SzczurekYT requested changes
Do not call a Vec cursor, because it is not a cursor.

2024-09-18 15:27 UTC, Norbiros commented
> So this just adds wrapper functions around current code which still use bytes right?

Yes, it's fine to use bytes. The problem was that if you wanted to interact with those methods in CrabNBT, you had to add `bytes` to your project. Now you can use temporary wrapper functions. Probably even in v1.0.0 we'll use bytes under the hood.

2024-09-18 15:28 UTC, SzczurekYT commented
> but this will require changes to public methods and a new major version (see #18 for details).

No, that is wrong.
From semver spec
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Until we release 1.0.0 we are allowed to break public api if needed.

2024-09-19 15:26 UTC, SzczurekYT approved these changes

2024-09-19 15:42 UTC, merged